#! python 3
# Password character checker - checks if password contains 8 characters,
# including at least one uppercase, lowercase and digit

import re

def check():
    pswd = input('Enter a password at least 8 characters long, containing at least both upper and lower case characters, and having at leat one digit: ')
    num_regex = re.compile(r'\d+')
    upper_regex = re.compile(r'[A-Z]+')
    lower_regex = re.compile(r'[a-z]+')

    mo_num = num_regex.search(pswd)
    mo_upper = upper_regex.search(pswd)
    mo_lower = lower_regex.search(pswd)
	# Check password length
    if len(pswd) <= 8:
        print ('\nEnter a password at least 8 characters long.\n')
        return False
	# Check if password contains a digit
    try:
        len(mo_num.group()) > 0
    except AttributeError:
            print ('\nEnter a password containing at least 1 digit.\n')
            return False
	# Check if password contains an uppercase character
    try:
        len(mo_upper.group()) > 0
    except AttributeError:
        print ('Enter a password containing at least 1 uppercase character.')
        return False
    # Check if password contains a lowercase character
    try:
        len(mo_lower.group()) > 0
    except AttributeError:
        print ('Enter a password containing at least 1 lowercase character.')
        return False
    
    return True

print(check())
input('Press enter to exit.')
